name: Upload to AWS S3 Bucket

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@master
      
    - name: Build PWA
      run: |
        npm i
        npx nx build --prod --outputPath=www
        
    - name: Deploy
      uses: reggionick/s3-deploy@v3
      with:
        folder: 'www'
        bucket: 's3://spackomagic.de'
        bucket-region: 'eu-central-1'
