on:
  push:
    branches:
    - master
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: npm install, build and deploy
      run: |
        ssh-keygen -R <hostname>
        ssh ${{ secrets.SSH }} -tt
        cd projects/spacko-magic
        sh build-and-start-frontend.sh
