on:
  push:
    branches:
    - master
    
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: npm install, build and deploy
      run: |
        cd projects/spacko-magic
        sh build-and-start-frontend.sh
